apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: exhauster
  labels:
    app: exhauster
spec:
  selector:
    matchLabels:
      app: exhauster
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: exhauster
        role: master
        tier: backend
    spec:
      containers:
      - name: exhauster
        image: ap3rture/exhauster:latest
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 8080
      - name: mongo
        image: mongo:latest
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 27017
